version: '2'

services:
  order-revision-db:
    image: mysql:5.7
    container_name: stocker
    restart: always
#    volumes:
#      - data:/var/lib/mysql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASS: password
      MYSQL_DATABASE: stocker
    networks:
      - default
volumes:
  data:

networks:
  default:
    external:
      name: docker-network