server:
  port: 8081
spring:
  application:
    name: rbc-code-challenge
    description: RBC Code Challenge
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stocker?useSSL=false
    username: root
    password: root

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto: update

spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB